CREATE TABLE IF NOT EXISTS `acquisizioniFatture` (
  `id` varchar(36) NOT NULL,
  `companyId` varchar(36) NOT NULL,
  `stato` enum('da_verificare','verificata','registrata','pagata','errore','annullata') NOT NULL DEFAULT 'da_verificare',
  `nomeFile` varchar(255) NOT NULL,
  `mimeType` varchar(100) NOT NULL,
  `dimensione` int NOT NULL,
  `fileKey` varchar(255) NOT NULL,
  `fileUrl` text NOT NULL,
  `hashFile` varchar(64) NOT NULL,
  `hashDocumento` varchar(64) NOT NULL,
  `parserVersion` varchar(20) NOT NULL,
  `versioneFatturaPa` varchar(20),
  `progressivoInvio` varchar(20),
  `tipoDocumento` varchar(10),
  `numeroDocumento` varchar(50) NOT NULL,
  `dataDocumento` date NOT NULL,
  `valuta` varchar(3) NOT NULL DEFAULT 'EUR',
  `fornitoreRagioneSociale` varchar(200) NOT NULL,
  `fornitorePartitaIva` varchar(20),
  `fornitoreCodiceFiscale` varchar(20),
  `fornitoreIndirizzo` text,
  `fornitoreEmail` varchar(200),
  `fornitoreIban` varchar(34),
  `soggettoId` varchar(36),
  `imponibile` int NOT NULL,
  `importoIva` int NOT NULL,
  `totale` int NOT NULL,
  `ritenute` int NOT NULL DEFAULT 0,
  `altriImporti` int NOT NULL DEFAULT 0,
  `metodoPagamento` varchar(100),
  `condizioniPagamento` varchar(20),
  `riepiloghiIvaJson` json,
  `scadenzeJson` json,
  `avvisiJson` json,
  `aiUsata` boolean NOT NULL DEFAULT false,
  `duplicatoDocumentoId` varchar(36),
  `documentoFinanziarioId` varchar(36),
  `confermataAt` datetime,
  `confermataBy` varchar(36),
  `errore` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(36),
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedBy` varchar(36),
  `deletedAt` timestamp NULL,
  `deletedBy` varchar(36),
  `version` int NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_acq_fatture_company_hash_file` (`companyId`,`hashFile`),
  KEY `idx_acq_fatture_company_stato` (`companyId`,`stato`),
  KEY `idx_acq_fatture_company_hash_doc` (`companyId`,`hashDocumento`)
);

CREATE TABLE IF NOT EXISTS `righeFattureAcquisite` (
  `id` varchar(36) NOT NULL,
  `companyId` varchar(36) NOT NULL,
  `acquisizioneId` varchar(36) NOT NULL,
  `numeroLinea` int NOT NULL,
  `codiceArticolo` varchar(100),
  `descrizione` text NOT NULL,
  `quantita` decimal(14,4),
  `unitaMisura` varchar(30),
  `prezzoUnitario` int NOT NULL,
  `totaleLinea` int NOT NULL,
  `aliquotaIva` int NOT NULL,
  `naturaIva` varchar(10),
  `categoriaId` varchar(36),
  `centroCostoId` varchar(36),
  `destinazione` enum('costo','magazzino','investimento','altro') NOT NULL DEFAULT 'costo',
  `fonteClassificazione` enum('storico_codice','storico_descrizione','regola','ai','manuale','non_classificata') NOT NULL DEFAULT 'non_classificata',
  `confidenza` int NOT NULL DEFAULT 0,
  `aggiornaMagazzino` boolean NOT NULL DEFAULT false,
  `prodottoId` varchar(36),
  `creaProdotto` boolean NOT NULL DEFAULT false,
  `nomeProdotto` varchar(255),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(36),
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedBy` varchar(36),
  `deletedAt` timestamp NULL,
  `deletedBy` varchar(36),
  `version` int NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_righe_fatture_acq_numero` (`acquisizioneId`,`numeroLinea`),
  KEY `idx_righe_fatture_company_acq` (`companyId`,`acquisizioneId`)
);

CREATE TABLE IF NOT EXISTS `regoleClassificazioneFatture` (
  `id` varchar(36) NOT NULL,
  `companyId` varchar(36) NOT NULL,
  `chiaveRegola` varchar(64) NOT NULL,
  `fornitorePartitaIva` varchar(20),
  `codiceArticolo` varchar(100),
  `descrizioneNormalizzata` varchar(255),
  `categoriaId` varchar(36) NOT NULL,
  `centroCostoId` varchar(36),
  `destinazione` enum('costo','magazzino','investimento','altro') NOT NULL DEFAULT 'costo',
  `prodottoId` varchar(36),
  `utilizzi` int NOT NULL DEFAULT 1,
  `ultimoUtilizzoAt` datetime NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(36),
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedBy` varchar(36),
  `deletedAt` timestamp NULL,
  `deletedBy` varchar(36),
  `version` int NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_regole_fatture_company_chiave` (`companyId`,`chiaveRegola`),
  KEY `idx_regole_fatture_company_fornitore` (`companyId`,`fornitorePartitaIva`)
);
